DEFAULT_PAGE_SIZE = 12
MAX_SKILLS_AUTOCOMPLETE = 10

PROJECT_STATUS_OPEN = 'open'
PROJECT_STATUS_CLOSED = 'closed'
PROJECT_STATUSES = [
    (PROJECT_STATUS_OPEN, 'Open'),
    (PROJECT_STATUS_CLOSED, 'Closed'),
]

PROJECT_NAME_MAX_LENGTH = 200
PROJECT_SKILL_NAME_MAX_LENGTH = 124
USER_NAME_MAX_LENGTH = 124
USER_PHONE_MAX_LENGTH = 12
USER_ABOUT_MAX_LENGTH = 256

PHONE_REGEX = r'^(8\d{10}|\+7\d{10})$'
